DROP TABLE IF EXISTS CITA;
DROP TABLE IF EXISTS FRANJA_HORARIA;

CREATE TABLE IF NOT EXISTS FRANJA_HORARIA (
    ID VARCHAR(64) PRIMARY KEY,
    FECHA_HORA_INICIO TIMESTAMP NOT NULL,
    FECHA_HORA_FIN TIMESTAMP NOT NULL,
    PROFESIONAL_O_SERVICIO_ID VARCHAR(64) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL CHECK (ESTADO IN ('DISPONIBLE', 'RESERVADA')),
    VERSION BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT CHK_FRANJA_HORARIA_RANGO CHECK (FECHA_HORA_INICIO < FECHA_HORA_FIN)
);

CREATE TABLE IF NOT EXISTS CITA (
    ID VARCHAR(64) PRIMARY KEY,
    PACIENTE_ID VARCHAR(64) NOT NULL,
    FRANJA_HORARIA_ID VARCHAR(64) NOT NULL UNIQUE,
    ESTADO VARCHAR(20) NOT NULL CHECK (ESTADO IN ('CONFIRMADA')),
    FECHA_HORA_CREACION TIMESTAMP NOT NULL,
    CONSTRAINT FK_CITA_FRANJA_HORARIA FOREIGN KEY (FRANJA_HORARIA_ID) REFERENCES FRANJA_HORARIA (ID)
);

CREATE INDEX IF NOT EXISTS IDX_CITA_PACIENTE ON CITA (PACIENTE_ID);
